export type CompanyStatus =
	| "active"
	| "dissolved"
	| "liquidation"
	| "receivership"
	| "administration"
	| "voluntary-arrangement"
	| "converted-closed"
	| "insolvency-proceedings";

export type CompanyType =
	| "private-unlimited"
	| "ltd"
	| "protected-cell-company"
	| "plc"
	| "old-public-company"
	| "private-limited-guarant-nsc-limited-exemption"
	| "limited-partnership"
	| "private-limited-guarant-nsc"
	| "converted-or-closed"
	| "private-unlimited-nsc"
	| "private-limited-shares-section-30-exemption"
	| "assurance-company"
	| "oversea-company"
	| "eeig"
	| "icvc-securities"
	| "icvc-warrant"
	| "icvc-umbrella"
	| "industrial-and-provident-society"
	| "northern-ireland"
	| "northern-ireland-other"
	| "llp"
	| "royal-charter"
	| "investment-company-with-variable-capital"
	| "unregistered-company"
	| "llp"
	| "other"
	| "european-public-limited-liability-company-se"
	| "scottish-partnership"
	| "charitable-incorporated-organisation"
	| "scottish-charitable-incorporated-organisation"
	| "further-education-or-sixth-form-college-corporation";

export type Country =
	| "Wales"
	| "England"
	| "Scotland"
	| "Great Britain"
	| "Not specified"
	| "United Kingdom"
	| "Northern Ireland";
